# @package _global_

dataset:
  view_sampler:
    num_context_views: 16
    num_target_views: 8
    min_distance_between_context_views: 64
    max_distance_between_context_views: 96
    context_gap_warm_up_steps: 30_000
    target_gap_warm_up_steps: 30_000
    initial_min_distance_between_context_views: 48
    initial_max_distance_between_context_views: 64
