name: "dc"
subfolder: null

pretrained_from: mit-han-lab/dc-ae-f32c32-sana-1.1-diffusers
kwargs:
  in_channels: 3
  latent_channels:  32
  scaling_factor: 0.41407
  encoder: 
    in_channels: 3
    latent_channels:  32
    width_list: [128,256,512,512,1024,1024]
    depth_list: [0,4,8,2,2,2]
    block_type: [ResBlock,ResBlock,ResBlock,EViT_GLU,EViT_GLU,EViT_GLU]


  decoder: 
    in_channels: 3
    latent_channels:  32
    width_list: [128,256,512,512,1024,1024]
    depth_list: [0,5,10,2,2,2]
    block_type: [ResBlock,ResBlock,ResBlock,EViT_GLU,EViT_GLU,EViT_GLU]
    norm: [bn2d,bn2d,bn2d,trms2d,trms2d,trms2d]
    act: [relu,relu,relu,silu,silu,silu]

  