name: video_dc

pretrained_from: checkpoints/F32T4C128_AE.safetensors


kwargs:
  model_name: dc-ae-f32t4c128
  in_channels: 3
  latent_channels: 128
  from_scratch: false
  is_training: false
  use_spatial_tiling: true
  use_temporal_tiling: true
  spatial_tile_size: 256
  temporal_tile_size: 32
  tile_overlap_factor: 0.25
  scaling_factor: 2.028
  disc_off_grad_ckpt: false