defaults:
  - view_sampler: bounded

name: dl3dv
root: ""
random_transform_extrinsics: false
shape: [256, 256] # [180, 320]
precomputed_latents: 
  context: false
  target: false
baseline_epsilon: 1e-3

make_baseline_1: false
augment: true
cameras_are_circular: false

# Kown Bug: refer to docs/KNOWN_BUGS.md
scale_focal_by_256: false
scale_context_focal_by_256: false

