defaults:
  - view_sampler: unbounded

name: latent
context_root: null
target_root: null
make_baseline_1: false
shape: [256, 256] # [180, 320]
cameras_are_circular: false
precomputed_latents: 
  context: true
  target: true
baseline_epsilon: 1e-3
cameras_are_circular: false
limit_context_downsample_factor: [1] # There is no temporal downsampling for contexts so always set to 1
limit_target_downsample_factor: [1] # Usually we also train for downsampling factor of 1 but you can modify as you wish

random_flip: True
context_latent_type: "va"
target_latent_type: "videodc"