defaults:
  - view_sampler: bounded

name: latent
shape: [256, 256]
target_root: null
context_root: null
baseline_epsilon: 1.0e-3
make_baseline: false
map_dict: null
limit_target_downsample_factor: [1]
limit_context_downsample_factor: [1]
random_flip: true
context_latent_type: "va"
target_latent_type: "videodc"
augment: true
cameras_are_circular: false
precomputed_latents: 
  context: true
  target: true

# Kown Bug: refer to docs/KNOWN_BUGS.md
scale_focal_by_256: false