name: evaluation_video

index_path: assets/evaluation_index/re10k_c12_128.json
temporal_downsample: 4
num_context_views: 12
num_target_views: 8
num_target_split: 1
max_cond_number: 3
chunk_index_gap: 4
offset: 0