"""
This repo is forked from [Boyuan Chen](https://boyuan.space/)'s research 
template [repo](https://github.com/buoyancy99/research-template). 
By its MIT license, you must keep the above sentence in `README.md` 
and the `LICENSE` file to credit the author.
"""

from typing import Callable
import torch
import torch.distributed as dist
from lightning.pytorch.utilities.rank_zero import rank_zero_only

import torch
import torch.distributed as dist

def _global_worker_info():
    # local worker info (per-process)
    wi = torch.utils.data.get_worker_info()
    if wi is None:
        worker_id, num_workers = 0, 1
    else:
        worker_id, num_workers = wi.id, wi.num_workers

    # ddp info (per-process)
    if dist.is_available() and dist.is_initialized():
        rank = dist.get_rank()
        world = dist.get_world_size()
    else:
        rank, world = 0, 1

    global_worker_id = rank * num_workers + worker_id
    global_worker_count = world * num_workers
    return global_worker_id, global_worker_count

def broadcast_from_zero(
    
    init_func: Callable[[], torch.Tensor], func: Callable[[], torch.Tensor]
) -> torch.Tensor:
    """
    Broadcasts the result of func() from rank 0 to all other processes.
    If distributed is not initialized, returns the result of func() directly.
    Args:
        init_func: function that initializes a tensor (will be overwritten)
        func: function that generates the tensor to broadcast from rank 0
    Returns:
        torch.Tensor: the tensor generated by func() on rank 0
    """
    if not dist.is_initialized():
        return func()
    tensor = init_func()
    if is_rank_zero:
        tensor = func()
    dist.broadcast(tensor, src=0)
    return tensor
